%YAML:1.0

cam0:
  T_imu_cam: #Pcini RctoI
    - [-1.0, 0.0, 0.0, 0.151]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1993.60752, 1993.60752, 955.56668, 506.10394] #fu, fv, cu, cv[1884,1887,954,505]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_75_decoded
cam1:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-1.0, 0.0, 0.0, -0.539]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1993.60752, 1993.60752, 955.56668, 506.10394] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_77_decoded
cam2:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-1.0, 0.0, 0.0, -0.195]
    - [0.0, 0.0, 1.0, 0.130]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [2]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1021.493213, 1025.494672, 992.817807, 532.756131] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_76_decoded
