%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 1.54006028e-2  # [ m / s^2 / sqrt(Hz) ]   1.5e-2( accel "white noise" )
  accelerometer_random_walk: 6.198078349e-3   # [ m / s^3 / sqrt(Hz) ].  6.19e-3( accel bias diffusion)
  gyroscope_noise_density: 2.658456090e-3     # [ rad / s / sqrt(Hz) ]  2.6e-3 ( gyro "white noise" )改动基本没差别了
  gyroscope_random_walk: 1.4465183e-4     # [ rad / s^2 / sqrt(Hz) ] 1.4e-4 ( gyro bias diffusion )
  model: calibrated
  rostopic: /imu_data
  time_offset: 0.0
  update_rate: 100.0
