%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 1896.453734 #2184.03691
Camera.fy: 1896.453734 #2184.03691
Camera.cx: 1130.935303 #1337.63834
Camera.cy: 445.681980 #539.2818

Camera.k1: 0.0 #-0.530347
Camera.k2: 0.0 #0.235839 #0.0
Camera.p1: 0.0 #-0.000678 #0.0
Camera.p2: 0.0 #0.002793 #0.0

Camera.width: 1920
Camera.height: 1080

# Camera frames per second 
Camera.fps: 20.0

# stereo baseline times fx
Camera.bf: 1398.758588

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 100

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 1080
LEFT.width: 1920
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.544048, 0.286162, 0.003227, -0.009358, 0.000000]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1854.41786,    0.     , 1019.62065,
            0.     , 1862.95981,  517.50204,
            0.     ,    0.     ,    1.     ]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.99979608, -0.01954625,  0.00507455,
          0.01935414,  0.99918273,  0.03548652,
         -0.00576403, -0.03538107,  0.99935727]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1993.60752,    0.     ,  955.56668,    0.     ,
            0.     , 1993.60752,  506.10394,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
RIGHT.height: 1080
RIGHT.width: 1920
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.519758, 0.215111, 0.004712, -0.013724, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1842.29107,    0.     , 1089.38349,
            0.     , 1850.18457,  498.44677,
            0.     ,    0.     ,    1.     ]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.99571716,  0.06700912,  0.06369541,
         -0.06476153,  0.99722488, -0.03672157,
         -0.06597932,  0.03243928,  0.99729355]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 1993.60752,     0.     ,   955.56668, -1369.55958,
             0.     ,  1993.60752,   506.10394,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
             
MID.height: 1080
MID.width: 1920
MID.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.304309, 0.070495, -0.002115, -0.000592, 0.000000]
MID.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1021.49321,    0.     ,  992.81781,
            0.     , 1025.49467,  532.75613,
            0.     ,    0.     ,    1.     ]
MID.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1. ,  0. ,  0. ,
          0. ,  1. ,  0. ,
          0. ,  0. ,  1. ]
MID.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1021.49321 ,   0.     , 992.81781,   0.     ,
           0.     , 1025.49467, 532.75613,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 30
ORBextractor.minThFAST: 10

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2500


