%YAML:1.0

cam0:
  T_imu_cam: #
    - [-1.0, 0.0, 0.0, 0.151]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1979.45350, 1979.45350, 951.53487, 538.19084] #fu, fv, cu, cv[1884,1887,954,505]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_75_decoded
cam1:
  T_imu_cam: #
    - [-1.0, 0.0, 0.0, -0.539]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1979.45350, 1979.45350, 951.53487, 538.19084] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_77_decoded
cam2:
  T_imu_cam: #RCtoI pCinI
    - [-1.0, 0.0, 0.0, -0.195]
    - [0.0, 0.0, 1.0, 0.130]
    - [0.0, 1.0, 0.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [2]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1118.0838, 1126.2542, 966.4004, 528.8921] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_76_decoded
