%YAML:1.0

cam0:
  T_imu_cam: #Pcini RctoI
    - [-1.0, 0.0, 0.0, 0.368]
    - [0.0, 0.0, 1.0, 1.68]
    - [0.0, 1.0, 0.0, -0.97]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1896.453734, 1896.453734, 1130.935303, 445.681980] #fu, fv, cu, cv[1884,1887,954,505]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_75_decoded
cam1:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-1.0, 0.0, 0.0, -0.368]
    - [0.0, 0.0, 1.0, 1.68]
    - [0.0, 1.0, 0.0, -0.97]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1896.453734, 1896.453734, 1130.935303, 445.681980] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_76_decoded
cam2:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-1.0, 0.0, 0.0, -0.08]
    - [0.0, 0.0, 1.0, 1.575]
    - [0.0, 1.0, 0.0, -1.04]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0,0.0,0.0,0.0]
  distortion_model: randan
  intrinsics: [1031.08771, 1035.46405, 940.24517, 515.86611] #fu, fv, cu, cv[1876,1878,1004,516]
  resolution: [1920, 1080]
  rostopic: /mdc_camera_instance_77_decoded
